#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Prov\Command\SetVhostCommand;

$application = new Application();

$application->add(new SetVhostCommand());

$application->run();
